export const POPULAR_ARTISTS = [
"Youngboy Never Broke Again",
"Juice WRLD",
"Lil Durk",
"Future",
"Lil Baby",
"Playboi Carti",
"$uicideBoy$",
"Lil Uzi Vert",
"Drake",
"Eminem",
"Lil Wayne",
"Jay-Z",
"Kanye West",
"A$AP Rocky",
"Kid Cudi",
"J. Cole",
"Kendrick Lamar",
"Gunna",
"Mac Miller",
"JID",
"Denzel Curry",
"Doechi",
"Vic Mensa",
"Isaiah Rashaad",
"Rick Ross",
"Joey Bada$$",
"Jeezy",
"Pusha T",
"21 Savage",
"Baby Keem",
"Freddie Gibbs",
"Nas",
"Lloyd Banks",
"Mobb Deep",
"MF DOOM",
"Conway The Machine",
"Run The Jewels",
"Killer Mike",
"Twista",
"Pimp C",
"Post Malone",
"Outkast",
"Tyler, The Creator",
"Shaboozey",
"Cardi B",
"Notorious BIG",
"2Pac",
"Snoop Dogg",
"Lupe Fiasco",
"GloRilla",
"Travis Scott",
"Justin Bieber",
"Taylor Swift",
"The Weeknd",
"Billie Eilish",
"Ariana Grande",
"Bruno Mars",
"Ed Sheeran",
"Gracie Abrams",
"Harry Styles",
"Rihanna",
"Chappel Roan",
"Frank Ocean",
"Mariah Carey",
"Britney Spears",
"Michael Jackson",
"Prince",
"Beyonce",
"Don Toliver",
"Charli xcx",
"Lady Gaga",
"Hozier",
"Lola Young",
"Jessie Murph",
"Olivia Rodrigo",
"sombr",
"Tate McRae",
"SZA",
"Dua Lipa",
"Lorde",
"Lana Del Rey",
"Teddy Swims",
"Sabrina Carpenter",
"Bad Bunny",
"Eagles",
"Elton John",
"The Doors",
"The Beatles",
"Bob Dylan",
"Fleetwood Mac",
"Black Sabbath",
"Ozzy Osbourne",
"Wham!",
"Toto",
"Depeche Mode",
"Tears for Fears",
"Jefferson Airplane",
"Neil Young",
"Crosby, Stills, and Nash",
"Carlos Santana",
"Billy Joel",
"David Bowie",
"Bruce Springsteen",
"Joni Mitchell",
"Aretha Franklin",
"Stevie Wonder",
"Leonard Cohen",
"AC/DC",
"Queen",
"Bon Jovi",
"Guns N' Roses",
"The Rolling Stones",
"Tom Petty",
"Paul Simon",
"Linkin Park",
"Coldplay",
"Modest Mouse",
"Amy Winehouse",
"Nirvana",
"Oasis",
"Foo Fighters",
"Green Day",
"Metallica",
"Radiohead",
"Artic Monkeys",
"Fall Out Boy",
"The Killers",
"The Strokes",
"The Shins",
"Alice in Chains",
"Pearl Jam",
"Rage Against The Machine",
"Brand New",
"Taking Back Sunday",
"Ramones",
"Incubus",
"Red Hot Chili Peppers",
"Blink-182",
"Benson Boone",
"Morgan Wallen",
"Alex Warren",
"Zach Bryan",
"Luke Combs",
"Townes Van Zandt",
"George Strait",
"Alan Jackson",
"Garth Brooks",
"Tim McGraw",
"The Chicks",
"Chris Stapleton",
"Johnny Cash",
  "Kacey Musgraves",
  "Megan Maroney",
  "Dolly Parton",
  "Ella Langley",
  "Brad Paisley",
  "Lainey Wilson",
  "Cody Johnson",
  "Other"
];

export const POPULAR_GENRES = [
  "Pop",
  "Rock",
  "Hip Hop",
  "R&B",
  "Country",
  "Jazz",
  "Blues",
  "Folk",
  "Electronic",
  "Metal",
  "Punk",
  "Reggae",
  "Soul",
  "Indie",
  "Alternative",
  "Disco",
  "Funk",
  "Gospel",
  "Latin",
  "Classical",
  "Ambient",
  "Synthwave",
  "Lo-fi",
  "Trap",
  "Grime",
  "House",
  "Techno",
  "Dubstep",
  "Ska",
  "Grunge",
  "Emo",
  "Symphonic Rock",
  "Psychedelic Rock",
  "Progressive Rock",
  "Hardcore Punk",
  "New Wave",
  "Dream Pop",
  "Shoegaze",
  "Americana",
  "Bluegrass",
  "Other"
];
