export const POPULAR_ARTISTS = [
  "Taylor Swift",
  "Bob Dylan",
  "Kendrick Lamar",
  "Billie Eilish",
  "Ed Sheeran",
  "Adele",
  "Drake",
  "Beyoncé",
  "Eminem",
  "Lady Gaga",
  "Freddie Mercury",
  "David Bowie",
  "Prince",
  "Michael Jackson",
  "Dolly Parton",
  "Johnny Cash",
  "Kurt Cobain",
  "Lana Del Rey",
  "Frank Ocean",
  "SZA",
  "Harry Styles",
  "Olivia Rodrigo",
  "The Weeknd",
  "Dua Lipa",
  "Post Malone",
  "Bruno Mars",
  "Rihanna",
  "Kanye West",
  "Jay-Z",
  "Nas",
  "Tupac Shakur",
  "Notorious B.I.G.",
  "Stevie Wonder",
  "Aretha Franklin",
  "Marvin Gaye",
  "Amy Winehouse",
  "Lorde",
  "Hozier",
  "Arctic Monkeys",
  "Radiohead",
  "The Beatles",
  "The Rolling Stones",
  "Led Zeppelin",
  "Pink Floyd",
  "Fleetwood Mac",
  "Joni Mitchell",
  "Leonard Cohen",
  "Paul Simon",
  "Bruce Springsteen",
  "Billy Joel",
  "Elton John",
  "Other"
];

export const POPULAR_GENRES = [
  "Pop",
  "Rock",
  "Hip Hop",
  "R&B",
  "Country",
  "Jazz",
  "Blues",
  "Folk",
  "Electronic",
  "Metal",
  "Punk",
  "Reggae",
  "Soul",
  "Indie",
  "Alternative",
  "Disco",
  "Funk",
  "Gospel",
  "Latin",
  "Classical",
  "Ambient",
  "Synthwave",
  "Lo-fi",
  "Trap",
  "Grime",
  "House",
  "Techno",
  "Dubstep",
  "Ska",
  "Grunge",
  "Emo",
  "Symphonic Rock",
  "Psychedelic Rock",
  "Progressive Rock",
  "Hardcore Punk",
  "New Wave",
  "Dream Pop",
  "Shoegaze",
  "Americana",
  "Bluegrass",
  "Other"
];
